name: Acceptance Stage

on:
  workflow_run:
    workflows: ["Create Artifact"]
    types:
      - completed

jobs:
  acceptance_tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Deploy to Acceptance Test Environment
        run: ./bin/deploy-to-acceptance-test-environment ${{ vars.DOCKER_HUB_REPOSITORY }}:${{ github.sha }}

      - name: Run Acceptance Tests
        run: ./bin/run-acceptance-tests http://localhost:3000

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
